{
 "title": "Spark",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Кластер Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cores Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_coresUsed_Value{job=\"spark-workers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores Used per Worker",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_worker_coresUsed_Value{job=\"spark-workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors per Worker",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_worker_executors_Value{job=\"spark-workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_worker_executors_Value{job=\"spark-workers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_apps_Value{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(metrics_worker_memFree_MB_Value{job=\"spark-workers\"}) / (sum(metrics_worker_memUsed_MB_Value{job=\"spark-workers\"}) + sum(metrics_worker_memFree_MB_Value{job=\"spark-workers\"})))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Worker (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (metrics_worker_memFree_MB_Value{job=\"spark-workers\"} / (metrics_worker_memUsed_MB_Value{job=\"spark-workers\"} + metrics_worker_memFree_MB_Value{job=\"spark-workers\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Value{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_waitingApps_Value{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Used per Worker (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "metrics_worker_memUsed_MB_Value{job=\"spark-workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free per Worker (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "metrics_worker_memFree_MB_Value{job=\"spark-workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(metrics_jvm_total_used_Value{type=\"gauges\", job=~\"spark-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "metrics_jvm_total_used_Value{type=\"gauges\", job=~\"spark-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}